#!/usr/bin/env python3
"""
GPU Kernel Preprocessor (Generated by Kimi 2.5)

Converts C-like kernel functions defined within #PRAGMA SHADER_BEGIN/END blocks
to GLSL compute shaders.

Usage:
    python gpu_preprocessor.py <input.c> [output_dir]

Example C kernel:
    #PRAGMA SHADER_BEGIN(local_size=64)
    void kernel_add(float* outputs, float* a, float* b){
        uint32_t x, y, z; // always defined.
        if (x >= outputs.length()) return;
        outputs[x] = a[x] + b[x];
    }
    #PRAGMA SHADER_END

C types are automatically converted to GLSL:
    - uint32_t, unsigned int -> uint
    - int32_t, int -> int
    - uint64_t, long long -> int64_t
    - int64_t, long -> int64_t
    - uint16_t, short -> int16_t
    - int16_t -> int16_t
    - uint8_t, char -> uint8_t
    - int8_t -> int8_t
    - float -> float
    - double -> double
    - 0.0f -> 0.0 (float literals)
"""

import re
import os
import sys


def preprocess_gpu_kernels(c_file_path, output_dir=None):
    """
    Preprocessor that extracts C-like kernel functions from #PRAGMA SHADER_BEGIN/END blocks
    and converts them to GLSL compute shaders.
    
    Args:
        c_file_path: Path to the C file containing kernel pragma blocks
        output_dir: Directory to output GLSL files (defaults to same directory as input)
    
    Returns:
        List of generated GLSL file paths
    """
    
    with open(c_file_path, 'r') as f:
        content = f.read()
    
    if output_dir is None:
        output_dir = os.path.dirname(c_file_path) or '.'
    os.makedirs(output_dir, exist_ok=True)
    
    shader_block_pattern = r'#PRAGMA\s+SHADER_BEGIN\s*\(\s*local_size\s*=\s*(\d+)\s*\)(.*?)#PRAGMA\s+SHADER_END'
    
    generated_files = []
    
    for match in re.finditer(shader_block_pattern, content, re.DOTALL):
        local_size = match.group(1)
        kernel_code = match.group(2).strip()
        
        glsl_code = parse_kernel_to_glsl(kernel_code, local_size)
        func_name = extract_function_name(kernel_code)
        output_path = os.path.join(output_dir, f"{func_name}.comp")
        
        with open(output_path, 'w') as f:
            f.write(glsl_code)
        
        generated_files.append(output_path)
        print(f"Generated: {output_path}")
    
    return generated_files


def extract_function_name(kernel_code):
    """Extract the function name from kernel signature."""
    match = re.search(r'void\s+(\w+)\s*\(', kernel_code)
    if match:
        return match.group(1)
    return "kernel"


def parse_kernel_to_glsl(kernel_code, local_size):
    """Convert C kernel code to GLSL compute shader."""
    
    # Find the function signature - starts with 'void' and ends with ')'
    func_match = re.search(r'(void\s+\w+\s*\([^)]*\))', kernel_code, re.DOTALL)
    if not func_match:
        raise ValueError("Could not find function signature")
    
    func_sig = func_match.group(1)
    
    # The body starts after the signature
    sig_end_pos = func_match.end()
    body_with_braces = kernel_code[sig_end_pos:].strip()
    
    # Parse parameters
    params = parse_parameters(func_sig)
    
    # Extract function name
    func_name = extract_function_name(func_sig)
    
    # Extract body content (inside braces)
    body_content = extract_body_content(body_with_braces)
    
    # Build GLSL output
    glsl_lines = ['#version 450', '']
    glsl_lines.append(f'layout(local_size_x = {local_size}) in;')
    glsl_lines.append('')
    
    # Generate buffer declarations
    for i, (param_type, param_name) in enumerate(params):
        glsl_type = c_type_to_glsl(param_type)
        glsl_lines.append(f'layout(set = 0, binding = {i}) buffer Buffer{i} {{')
        glsl_lines.append(f'    {glsl_type} data[];')
        glsl_lines.append(f'}} {param_name};')
    
    glsl_lines.append('')
    glsl_lines.append('void main() {')
    
    # Add automatic x, y, z definitions
    glsl_lines.append('    uint x = gl_GlobalInvocationID.x;')
    glsl_lines.append('    uint y = gl_GlobalInvocationID.y;')
    glsl_lines.append('    uint z = gl_GlobalInvocationID.z;')
    
    # Transform body content
    transformed_body = transform_body(body_content, params)
    
    # Add body lines preserving relative indentation
    for line in transformed_body.split('\n'):
        stripped = line.rstrip()
        if stripped:
            glsl_lines.append(stripped)
    
    glsl_lines.append('}')
    
    return '\n'.join(glsl_lines)


def parse_parameters(func_sig):
    """Extract parameters from function signature."""
    match = re.search(r'\((.*)\)', func_sig, re.DOTALL)
    if not match:
        return []
    
    params_str = match.group(1)
    params_str = ' '.join(params_str.split())
    
    param_parts = [p.strip() for p in params_str.split(',')]
    
    params = []
    for part in param_parts:
        if not part:
            continue
        # Match: type* name or type *name (type can include spaces like "unsigned int")
        param_match = re.search(r'((?:\w+\s+)?\w+)\s*\*\s*(\w+)', part)
        if param_match:
            type_name = param_match.group(1).strip()
            var_name = param_match.group(2)
            params.append((type_name, var_name))
    
    return params


def c_type_to_glsl(c_type):
    """Convert C type to GLSL type."""
    type_map = {
        'float': 'float',
        'double': 'double',
        'int': 'int',
        'int32_t': 'int',
        'uint32_t': 'uint',
        'uint': 'uint',
        'unsigned': 'uint',
        'unsigned int': 'uint',
        'unsignedint': 'uint',
        'long': 'int64_t',
        'long long': 'int64_t',
        'short': 'int16_t',
        'char': 'int8_t',
        'bool': 'bool',
    }
    lookup_type = c_type.replace(' ', '')
    return type_map.get(lookup_type, 'float')


def extract_body_content(body_text):
    """Extract content inside the outermost braces."""
    body_text = body_text.strip()
    
    if not body_text.startswith('{'):
        return body_text
    
    brace_count = 1
    i = 1
    while i < len(body_text) and brace_count > 0:
        if body_text[i] == '{':
            brace_count += 1
        elif body_text[i] == '}':
            brace_count -= 1
        i += 1
    
    return body_text[1:i-1]


def transform_body(body, params):
    """Transform C body to GLSL body."""
    lines = body.split('\n')
    result_lines = []
    
    param_names = [p[1] for p in params]
    
    # Calculate base indentation to strip
    base_indent = None
    for line in lines:
        stripped = line.lstrip()
        if stripped:
            indent = len(line) - len(stripped)
            if base_indent is None or indent < base_indent:
                base_indent = indent
    
    if base_indent is None:
        base_indent = 0
    
    for line in lines:
        # Strip base indentation and process
        if len(line) >= base_indent:
            line = line[base_indent:]
        
        stripped = line.strip()
        
        # Skip the automatic x, y, z declarations
        if re.match(r'\s*(uint32_t|uint|unsigned\s+int)\s+(x|y|z)\s*[,;]', stripped):
            if 'always defined' in stripped.lower() or stripped.endswith(','):
                continue
        
        # Skip comments that mention "always defined"
        if 'always defined' in stripped.lower():
            continue
        
        # Remove C++ style comments (/// or //)
        line = re.sub(r'\s*///.*$', '', line)
        line = re.sub(r'\s*//.*$', '', line)
        
        # Transform .length() calls and array indexing
        for param_name in param_names:
            pattern_length = rf'\b{re.escape(param_name)}\s*\.\s*length\s*\(\s*\)'
            line = re.sub(pattern_length, f'{param_name}.data.length()', line)
            
            pattern_index = rf'\b{re.escape(param_name)}\s*\[([^\]]+)\]'
            line = re.sub(pattern_index, rf'{param_name}.data[\1]', line)
        
        # Convert C types to GLSL types in variable declarations
        line = convert_c_types_to_glsl(line)
        
        # Convert float literals (0.0f -> 0.0)
        line = re.sub(r'\b(\d+\.\d*)f\b', r'\1', line)
        line = re.sub(r'\b(\d*\.\d+)f\b', r'\1', line)
        
        # Add base indentation (4 spaces for main body)
        if line.strip():
            result_lines.append('    ' + line.rstrip())
    
    return '\n'.join(result_lines)


def convert_c_types_to_glsl(line):
    """Convert C type declarations to GLSL types."""
    type_conversions = [
        # Fixed-width integer types
        (r'\buint32_t\b', 'uint'),
        (r'\bint32_t\b', 'int'),
        (r'\buint64_t\b', 'uint64_t'),
        (r'\bint64_t\b', 'int64_t'),
        (r'\buint16_t\b', 'uint16_t'),
        (r'\bint16_t\b', 'int16_t'),
        (r'\buint8_t\b', 'uint8_t'),
        (r'\bint8_t\b', 'int8_t'),
        # Standard C types
        (r'\bunsigned int\b', 'uint'),
        (r'\bunsigned\b(?=\s+\w)', 'uint'),  # unsigned followed by variable name
        (r'\blong long\b', 'int64_t'),
        (r'\bshort\b', 'int16_t'),
        (r'\bchar\b', 'int8_t'),
    ]
    
    for pattern, replacement in type_conversions:
        line = re.sub(pattern, replacement, line)
    
    return line


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: python gpu_preprocessor.py <input.c> [output_dir]")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_dir = sys.argv[2] if len(sys.argv) > 2 else None
    
    if not os.path.exists(input_file):
        print(f"Error: File '{input_file}' not found.")
        sys.exit(1)
    
    generated = preprocess_gpu_kernels(input_file, output_dir)
    
    if generated:
        print(f"\nSuccessfully generated {len(generated)} shader(s):")
        for path in generated:
            print(f"  - {path}")
    else:
        print("No kernel blocks found in the input file.")