#version 450
layout(local_size_x = 64) in;

layout(binding = 0) buffer State {
    float values[];
};

layout(binding = 1) buffer Operations {
    uint update_idxs[];
};

layout(binding = 2, std430) coherent buffer Counter {
    uint counter;
};

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= values.length()) return;

    if (values[i] > 0.0) {
        uint index = atomicAdd(counter, 1);
        update_idxs[index] = i;
    }
}